CREATE TABLE IF NOT EXISTS users (
	id CHAR(4) CONSTRAINT user_id PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS classes (
	id CHAR(4) CONSTRAINT class_id PRIMARY KEY,
	name VARCHAR(10) NOT NULL,
	teacher_name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS students (
	id CHAR(4) CONSTRAINT student_id PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	gender INTEGER NOT NULL,
	photo_base_64 text,
	class_id CHAR(4) REFERENCES classes(id)
);